on:
  push:
    branches:
    - main

jobs:
  build:
    name: build application
    runs-on: ubuntu-latest
    steps:
    - name: menampilkan text
      run: echo "ini step untuk build aplikasi"

  test:
    name: test application
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: menampilkan text
      run: echo "ini step untuk test aplikasi"

  deploy:
    name: deploy application
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: menampilkan text
      run: echo "ini step untuk deploy aplikasi"
    - name: deploy aplikasi ke server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          rm -rf APP-BE-STUDIDEVOPS
          git clone git@github.com:Blessed-Code/APP-BE-STUDIDEVOPS.git
          cd APP-BE-STUDIDEVOPS/
          npm install
          sudo service nginx restart

  notif:
    name: deploy application
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
